### ISSUE TITLE
Wrong example for role for new service

### ISSUE THREAD

**Issue by rddefauw** [aws-samples/aws-developer-workshop#33]
The instructions show these lines for the new Lambda function role:

```
Role:
      Fn::ImportValue:
        !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
```

That doesn't work.  The role should be defined in the same way as the HelloWorld service

**Comment by ronaldwidha** [comment]
fixed in #31
